### Deleta um item específico do menu
DELETE http://localhost:3000/menu/2

###
# O separador ### é importante para separar as requisições

### Lista todos os itens do menu (para verificar se o item foi deletado)
GET http://localhost:3000/menu/

###

### Atualiza o preço de um item
PUT http://localhost:3000/menu/1
Content-Type: application/json

{
  "preco": 32.50
}

###

### Cria um novo item no cardápio
POST http://localhost:3000/menu
Content-Type: application/json

{
  "nome": "Batata Frita",
  "descricao": "Porção de batatas fritas crocantes.",
  "preco": 15.0,
  "categoria": "Acompanhamentos",
  "disponivel": true
}

###